require "yaml"
require "json"
require "kemal"

require "./util/platform"
require "./util/paths"
require "./util/process_runner"
require "./util/logging"
require "./core/result"
require "./config"
require "./profiles/id_generator"
require "./profiles/profile"
require "./profiles/parser"
require "./profiles/validator"
require "./profiles/store"
require "./caddy/backend"
require "./caddy/portable_backend"
require "./caddy/snippets"
require "./caddy/validator"
require "./caddy/reloader"
require "./caddy/manager"
require "./services/adapter"
require "./services/mac_brew_adapter"
require "./services/manager"
require "./core/actions"
require "./core/state"
require "./auth"
require "./web/render"
require "./web/routes"
require "./server"
require "./cli"

Patty::CLI.run(ARGV)
